name = "dashboard-iegm"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# ConfiguraÃ§Ã£o para Pages
[env.production]
d1_databases = [{ binding = "DB", database_name = "dataset-iegm", database_id = "dcb723ba-b7ee-4851-8fb4-6fe106279b01" }]

[env.development]
d1_databases = [{ binding = "DB", database_name = "dataset-iegm-dev", database_id = "dcb723ba-b7ee-4851-8fb4-6fe106279b01" }]